# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'backpack.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(830, 510)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.encrypt.setGeometry(QtCore.QRect(20, 350, 121, 41))
        self.encrypt.setObjectName("encrypt")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 30, 191, 21))
        self.label_4.setObjectName("label_4")
        self.decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.decrypt.setGeometry(QtCore.QRect(180, 350, 121, 41))
        self.decrypt.setObjectName("decrypt")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(340, 30, 181, 21))
        self.label_5.setObjectName("label_5")
        self.save = QtWidgets.QPushButton(self.centralwidget)
        self.save.setGeometry(QtCore.QRect(660, 30, 121, 41))
        self.save.setObjectName("save")
        self.load = QtWidgets.QPushButton(self.centralwidget)
        self.load.setGeometry(QtCore.QRect(660, 80, 121, 41))
        self.load.setObjectName("load")
        self.mes = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.mes.setGeometry(QtCore.QRect(30, 60, 261, 41))
        self.mes.setObjectName("mes")
        self.dec_mes = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.dec_mes.setGeometry(QtCore.QRect(330, 60, 191, 41))
        self.dec_mes.setObjectName("dec_mes")
        self.open_key = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.open_key.setGeometry(QtCore.QRect(30, 130, 261, 41))
        self.open_key.setObjectName("open_key")
        self.close_key = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.close_key.setGeometry(QtCore.QRect(30, 190, 261, 41))
        self.close_key.setObjectName("close_key")
        self.n = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.n.setGeometry(QtCore.QRect(30, 260, 61, 41))
        self.n.setObjectName("n")
        self.n1 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.n1.setGeometry(QtCore.QRect(130, 260, 61, 41))
        self.n1.setObjectName("n1")
        self.m = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.m.setGeometry(QtCore.QRect(230, 260, 61, 41))
        self.m.setObjectName("m")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 110, 191, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 170, 191, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(50, 240, 21, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(150, 240, 31, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(250, 240, 21, 21))
        self.label_10.setObjectName("label_10")
        self.plainTextEdit_6 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_6.setGeometry(QtCore.QRect(330, 170, 471, 271))
        self.plainTextEdit_6.setObjectName("plainTextEdit_6")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(530, 140, 191, 21))
        self.label_11.setObjectName("label_11")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.encrypt.setText(_translate("MainWindow", "Зашифровать"))
        self.label_4.setText(_translate("MainWindow", "Сообщение для шифрования"))
        self.decrypt.setText(_translate("MainWindow", "Дешифровать"))
        self.label_5.setText(_translate("MainWindow", "Зашифрованное сообщение"))
        self.save.setText(_translate("MainWindow", "Сохранить"))
        self.load.setText(_translate("MainWindow", "Загрузить"))
        self.label_6.setText(_translate("MainWindow", "Открытый ключ"))
        self.label_7.setText(_translate("MainWindow", "Закрытый ключ"))
        self.label_8.setText(_translate("MainWindow", "n"))
        self.label_9.setText(_translate("MainWindow", "n^-1"))
        self.label_10.setText(_translate("MainWindow", "m"))
        self.label_11.setText(_translate("MainWindow", "Зашифровка"))
