# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'el_gamal.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(830, 510)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.encrypt.setGeometry(QtCore.QRect(530, 30, 121, 41))
        self.encrypt.setObjectName("encrypt")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 30, 281, 21))
        self.label_4.setObjectName("label_4")
        self.decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.decrypt.setGeometry(QtCore.QRect(530, 80, 121, 41))
        self.decrypt.setObjectName("decrypt")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(340, 30, 181, 21))
        self.label_5.setObjectName("label_5")
        self.save = QtWidgets.QPushButton(self.centralwidget)
        self.save.setGeometry(QtCore.QRect(660, 30, 121, 41))
        self.save.setObjectName("save")
        self.load = QtWidgets.QPushButton(self.centralwidget)
        self.load.setGeometry(QtCore.QRect(660, 80, 121, 41))
        self.load.setObjectName("load")
        self.mes = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.mes.setGeometry(QtCore.QRect(30, 60, 271, 41))
        self.mes.setObjectName("mes")
        self.dec_mes = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.dec_mes.setGeometry(QtCore.QRect(330, 60, 191, 41))
        self.dec_mes.setObjectName("dec_mes")
        self.mes_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.mes_2.setGeometry(QtCore.QRect(160, 190, 91, 41))
        self.mes_2.setObjectName("mes_2")
        self.mes_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.mes_3.setGeometry(QtCore.QRect(30, 190, 91, 41))
        self.mes_3.setObjectName("mes_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(160, 170, 101, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 170, 121, 21))
        self.label_7.setObjectName("label_7")
        self.mes_4 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.mes_4.setGeometry(QtCore.QRect(270, 190, 91, 41))
        self.mes_4.setObjectName("mes_4")
        self.mes_5 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.mes_5.setGeometry(QtCore.QRect(380, 190, 91, 41))
        self.mes_5.setObjectName("mes_5")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(270, 170, 101, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(380, 170, 101, 21))
        self.label_9.setObjectName("label_9")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.encrypt.setText(_translate("MainWindow", "Зашифровать"))
        self.label_4.setText(_translate("MainWindow", "Сообщение для шифрования эль-гамалям"))
        self.decrypt.setText(_translate("MainWindow", "Дешифровать"))
        self.label_5.setText(_translate("MainWindow", "Зашифрованное сообщение"))
        self.save.setText(_translate("MainWindow", "Сохранить"))
        self.load.setText(_translate("MainWindow", "Загрузить"))
        self.label_6.setText(_translate("MainWindow", "Открытый ключ"))
        self.label_7.setText(_translate("MainWindow", "Закрытый ключ"))
        self.label_8.setText(_translate("MainWindow", "Открытый ключ"))
        self.label_9.setText(_translate("MainWindow", "Открытый ключ"))
