# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gamma.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(728, 510)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.encrypt.setGeometry(QtCore.QRect(60, 240, 121, 41))
        self.encrypt.setObjectName("encrypt")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(440, 60, 221, 21))
        self.label_2.setObjectName("label_2")
        self.gamma = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.gamma.setGeometry(QtCore.QRect(440, 80, 271, 41))
        self.gamma.setObjectName("gamma")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 60, 321, 21))
        self.label_4.setObjectName("label_4")
        self.decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.decrypt.setGeometry(QtCore.QRect(220, 240, 121, 41))
        self.decrypt.setObjectName("decrypt")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 150, 311, 21))
        self.label_5.setObjectName("label_5")
        self.save = QtWidgets.QPushButton(self.centralwidget)
        self.save.setGeometry(QtCore.QRect(60, 300, 121, 41))
        self.save.setObjectName("save")
        self.load = QtWidgets.QPushButton(self.centralwidget)
        self.load.setGeometry(QtCore.QRect(220, 300, 121, 41))
        self.load.setObjectName("load")
        self.mes = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.mes.setGeometry(QtCore.QRect(60, 80, 271, 41))
        self.mes.setObjectName("mes")
        self.dec_mes = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.dec_mes.setGeometry(QtCore.QRect(60, 170, 271, 41))
        self.dec_mes.setObjectName("dec_mes")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.encrypt.setText(_translate("MainWindow", "Зашифровать"))
        self.label_2.setText(_translate("MainWindow", "Гамма"))
        self.label_4.setText(_translate("MainWindow", "Сообщение для шифрования гаммированием"))
        self.decrypt.setText(_translate("MainWindow", "Дешифровать"))
        self.label_5.setText(_translate("MainWindow", "Зашифрованное сообщение"))
        self.save.setText(_translate("MainWindow", "Сохранить"))
        self.load.setText(_translate("MainWindow", "Загрузить"))
