# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uitson.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(888, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.encrypt.setGeometry(QtCore.QRect(740, 240, 121, 41))
        self.encrypt.setObjectName("encrypt")
        self.pleifer_key = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pleifer_key.setGeometry(QtCore.QRect(30, 80, 201, 41))
        self.pleifer_key.setObjectName("pleifer_key")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 60, 221, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(350, 60, 221, 21))
        self.label_2.setObjectName("label_2")
        self.pleifer_mes = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pleifer_mes.setGeometry(QtCore.QRect(350, 80, 271, 41))
        self.pleifer_mes.setObjectName("pleifer_mes")
        self.mes = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.mes.setGeometry(QtCore.QRect(450, 230, 281, 111))
        self.mes.setObjectName("mes")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 200, 171, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(450, 210, 321, 21))
        self.label_4.setObjectName("label_4")
        self.decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.decrypt.setGeometry(QtCore.QRect(740, 300, 121, 41))
        self.decrypt.setObjectName("decrypt")
        self.dec_mes = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.dec_mes.setGeometry(QtCore.QRect(450, 410, 281, 111))
        self.dec_mes.setObjectName("dec_mes")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(450, 390, 311, 21))
        self.label_5.setObjectName("label_5")
        self.save = QtWidgets.QPushButton(self.centralwidget)
        self.save.setGeometry(QtCore.QRect(740, 420, 111, 41))
        self.save.setObjectName("save")
        self.load = QtWidgets.QPushButton(self.centralwidget)
        self.load.setGeometry(QtCore.QRect(740, 480, 111, 41))
        self.load.setObjectName("load")
        self.matrix_pleifera = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.matrix_pleifera.setGeometry(QtCore.QRect(650, 80, 211, 121))
        self.matrix_pleifera.setObjectName("matrix_pleifera")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(650, 60, 221, 21))
        self.label_6.setObjectName("label_6")
        self.matrix_uitson1 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.matrix_uitson1.setGeometry(QtCore.QRect(240, 230, 191, 291))
        self.matrix_uitson1.setObjectName("matrix_uitson1")
        self.matrix_vigenera_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.matrix_vigenera_3.setGeometry(QtCore.QRect(30, 230, 191, 291))
        self.matrix_vigenera_3.setObjectName("matrix_vigenera_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.encrypt.setText(_translate("MainWindow", "Зашифровать"))
        self.label.setText(_translate("MainWindow", "Ключ для шифрования Плейфера"))
        self.label_2.setText(_translate("MainWindow", "Сообщение ключ для Плейфера"))
        self.label_3.setText(_translate("MainWindow", "Алфавиты Уитсона"))
        self.label_4.setText(_translate("MainWindow", "Сообщение для шифрования шифром Уитсона"))
        self.decrypt.setText(_translate("MainWindow", "Дешифровать"))
        self.label_5.setText(_translate("MainWindow", "Зашифрованное сообщение шифром Уитсона"))
        self.save.setText(_translate("MainWindow", "Сохранить"))
        self.load.setText(_translate("MainWindow", "Загрузить"))
        self.label_6.setText(_translate("MainWindow", "Алфавит Плейфера"))
