# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'magic_square_layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 19, 321, 471))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.message_enc = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.message_enc.setObjectName("message_enc")
        self.verticalLayout.addWidget(self.message_enc)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.matrix1 = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.matrix1.setObjectName("matrix1")
        self.horizontalLayout.addWidget(self.matrix1)
        self.matrix2 = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.matrix2.setObjectName("matrix2")
        self.horizontalLayout.addWidget(self.matrix2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.enc_mes = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.enc_mes.setObjectName("enc_mes")
        self.verticalLayout.addWidget(self.enc_mes)
        self.enc_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.enc_btn.setObjectName("enc_btn")
        self.verticalLayout.addWidget(self.enc_btn)
        self.opne_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.opne_btn.setObjectName("opne_btn")
        self.verticalLayout.addWidget(self.opne_btn)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(350, 20, 341, 471))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.message_dec = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget_2)
        self.message_dec.setObjectName("message_dec")
        self.verticalLayout_2.addWidget(self.message_dec)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.key1 = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget_2)
        self.key1.setObjectName("key1")
        self.verticalLayout_2.addWidget(self.key1)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.dec_mes = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget_2)
        self.dec_mes.setObjectName("dec_mes")
        self.verticalLayout_2.addWidget(self.dec_mes)
        self.dec_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.dec_btn.setObjectName("dec_btn")
        self.verticalLayout_2.addWidget(self.dec_btn)
        self.save_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.save_btn.setObjectName("save_btn")
        self.verticalLayout_2.addWidget(self.save_btn)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Magic square"))
        self.label.setText(_translate("MainWindow", "Message for encrypt"))
        self.label_3.setText(_translate("MainWindow", "Matrixs"))
        self.label_6.setText(_translate("MainWindow", "Encrypted message"))
        self.enc_btn.setText(_translate("MainWindow", "Encrypt"))
        self.opne_btn.setText(_translate("MainWindow", "Open"))
        self.label_2.setText(_translate("MainWindow", "Message for decrypt"))
        self.label_4.setText(_translate("MainWindow", "Key"))
        self.label_5.setText(_translate("MainWindow", "Decrypted message"))
        self.dec_btn.setText(_translate("MainWindow", "Decrypt"))
        self.save_btn.setText(_translate("MainWindow", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())